; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32@6.7.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  adafruit/Adafruit NeoPixel@^1.12.3
