// Generated by webui/build.mjs. Do not edit.
#pragma once

#include "web/portal_assets.h"

namespace web_assets {
extern const portal_assets::WebAsset ROOT_PAGE;
extern const portal_assets::WebAsset WIFI_PAGE;
extern const portal_assets::WebAsset CONFIG_PAGE;
extern const portal_assets::WebAsset DEV_PAGE;
} // namespace web_assets
